// <auto-generated />
namespace TraXomHRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3rdMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3rdMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201706221624531_3rdMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
